### ISSUE TITLE
用CSS给加载失败的图片添加样式

### ISSUE THREAD

**Issue by jwenjian** [jwenjian/reading-list#71]
https://dev.to/sasscrafter/how-to-style-broken-images-with-css-4il2

---

通常情况下, 伪元素 `::before` 和 `::after` 对于 `<img>` 标签不起作用, 但是如果一个图片加载失败, `::before` 和 `::after` 就会显示, 利用这个特性就可以写出如下 CSS 来给加载失败的图片添加样式

```css
img {
     display: inline-block;
     font-family: Arial, sans-serif;
     font-weight: 300;
     line-height: 2;
     text-align: center;

     min-width: 300px;
     min-height: 50px;
     position: relative;
}

img::before {
     content: '';
     width: 100%;
     height: calc(100% + 10px);
     background-color: #ccc;
     border-radius: 10px;
     position: absolute;
     top: 50%;
     left: -2px;
     transform: translateY(-50%);
 }


img::after {
     content: "\2639" " " attr(alt);

     font-size: 18px;
     color: rgb(100, 100, 100);

     display: block;
     position: absolute;
     z-index: 2;
     top: 5px;
     left: 0;
     width: 100%;
     height: 100%;
}


```
